# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:8.1
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - php -v
          - apt-get update
          - apt-get install -y unzip git
          - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          #          - composer install
          - git push https://heroku:dc58666a-61f5-4657-8340-d14678b75357@git.heroku.com/jeeni-laravel.git HEAD
          - export CACHE_DRIVER=redis
          - export SESSION_DRIVER=redis
          - export DB_CONNECTION=heroku_mysql_connection
          - composer update
          - php -r "copy('.env.pipelines', '.env');"
          - php artisan migrate
          - php artisan storage:link