@extends('front.layouts.master')

@section('page_title') Privacy - Jeeni @endsection

@section('content')
    <main>
        <!-- Body content -->
        <div class="container-xl py-5 body-content">

        @include('front.layouts.sub-header', ['page_heading' => 'Terms <span class="fw-normal">and Conditions</span>'])

            <!-- Content after the title -->
            <div class="row pb-3 pb-md-5">
                <!-- Content Wrapper -->
                <div class="d-block">
                    <!-- Terms Condition -->
                    <h6 class="fw-bolder mt-4 text-danger">WELCOME</h6>
                    <p>Hello, and welcome to our Jeeni Terms and Conditions of Use. Here’s what they do:</p>
                    <p class="m-1"><i class="bi bi-check2 me-2"></i>Outline your legal rights on Jeeni</p>
                    <p class="m-1"><i class="bi bi-check2 me-2"></i>Explain the rights you give to us when you use Jeeni</p>
                    <p class="m-1"><i class="bi bi-check2 me-2"></i>Describe the rules you need to follow when you use Jeeni</p>
                    <p class="m-1"><i class="bi bi-check2 me-2"></i>Include a neat class-action waiver and agreement about resolving any disputes that may arise between us, as if.</p>
                    <p>So, please read through these Terms and Conditions carefully, and read our Jeeni Privacy Policy too. You won’t regret it.</p>

                    <h6 class="fw-bolder mt-4 text-danger">AGREEMENT TO THESE TERMS AND CONDITIONS</h6>
                    <p>By clicking the agreement check-box when you join Jeeni, you are declaring that you agree to all this stuff, and that you are old enough to have a credit card or operate an online payment account in whatever country you live. We’re based in the United Kingdom where the age to do that is 18. If you’re under-age, that’s fine, and by clicking the agreement checkbox your parent or guardian agrees to take legal responsibility for your involvement with Jeeni. As for viewing Jeeni content, you need to be aged over 13 and ready to enjoy yourself. Also, whoever you are, you need to have the power to enter a binding contract with us and not be barred from doing so under any laws that apply to you.</p>
                    <p>By clicking the agreement check-box and appying to join Jeeni, you are agreeing to receive the Jeeni Newsletter at the email address you have given. You can unsubscribe from the Newsletter at any time, and an opt-out is included in every issue.</p>
                    <p>These Terms and Conditions may change from time to time, and it’s up to you to review them right here on this page. All the time you are a signed-up member of Jeeni, you acknowledge that you have read and understand what’s on this page, and you agree to be bound by it. If you don’t agree with it, or can’t comply with it, then go get your thrills somewhere else.</p>
                    <p>Nobody can predict the future, and we may make changes to your Jeeni service for really good reasons, like adding new functions or features, embracing the latest science and technology, beefing up our security, and of course for legal or regulatory reasons. We may also change membership details, offers, deals, charges and other important stuff. When we make material changes like that, we’ll let you know as best we can, either by displaying a notice in your face, or seeking your agreement within Jeeni itself, or by sending you an email. In some cases, we’ll notify you in advance, and your continued use of Jeeni after the changes have been made mean you accept the changes. If you don’t want to continue using Jeeni for any reason, that’s fine by us. If you got your membership or Jeeni deal through a third party, we haven’t got the power or inclination to get involved, and you must cancel the applicable membership through that third party.</p>

                    <h6 class="fw-bolder mt-4 text-danger">YOU</h6>
                    <p>So, you or your account-holder are over the legal age, and legally valid. If you join Jeeni on behalf of a company, organization, entity, or brand, then all these terms apply to both you as an individual and/or that company, organization, entity, or brand. Your password protects your user account, and you are solely responsible for keeping your password confidential and secure. You understand that you are responsible for all use of your username and password on Jeeni. If your username or password is lost or stolen, or if you believe there has been unauthorised access to your account by a third party, you must change your password as soon as possible.</p>

                    <h6 class="fw-bolder mt-4 text-danger">RIPPING OFF JEENI WEBSITES, APPS & SOCIAL MEDIA</h6>
                    <p>OK, we know you’re going to do it anyway, so we may as well give you permission to view, link to, link from, download, copy, print and generally mess around with the content of Jeeni websites, apps and social media, as long as the content is not modified or altered in any way. But you may not claim it as your own. And you may not use any Jeeni trademark, logo, or proprietary stuff like images, text, page layout, forms or any bits of code unless you get our consent first. You do not acquire any ownership rights to any Jeeni online content, unless you uploaded this content yourself and unless it is your legal copyright. Any unauthorized use of Jeeni stuff may end your Jeeni membership, and you may lose any paid services or subscriptions without refund.</p>

                    <h6 class="fw-bolder mt-4 text-danger">OUR SERVICE</h6>
                    <p>The Jeeni service and content are the property of Jeeni or our licensors. We grant you limited, non-exclusive access to make use of the Jeeni service, and this access shall remain in effect until and unless you leave us or we leave you. Jeeni software applications and the Jeeni platform are not sold or transferred to you, and Jeeni and its licensors retain ownership of all copies of Jeeni applications and the Jeeni platform after installation on your personal computers, mobile handsets, tablets, wearable devices, speakers, and any other devices whether they exist now or in the future, anywhere in the solar system. Or other solar systems.</p>

                    <h6 class="fw-bolder mt-4 text-danger">PAYMENT</h6>
                    <p>Jeeni is free to join and free to enjoy for all viewers. If you’re a free Jeeni viewer, then of course you don’t pay, but you do need to give us a few contact details so we can wheedle and bribe you whenever we feel like it. This is the bit where we talk about paying for artist subscriptions. Payment is really straightforward, if you decide you want all the extras and services offered to artists, then you pay for them. Simple as that.</p>
                    <p>The price for paid Jeeni extras and subscriptions may go up or down from time to time, and of course we’ll tell you about price changes advance. Any price changes will take effect at the start of your next subscription period following the date of when we tell you about it. Subject to applicable law, you accept the new price by continuing to use the Jeeni service after the price change takes effect. Obviously, you can reject the change by unsubscribing from Jeeni at any time before the price change goes into effect.</p>

                    <h6 class="fw-bolder mt-4 text-danger">CANCELLATION</h6>
                    <p>Users of Jeeni services can cancel their membership, participation, and subscriptions at any time, for any reason. No hassle, no quibble, no ifs, no buts. We’ll store your data for 30 days in case you change your mind, and then we’ll delete your account, including your profile, showcase, videos, rewards, fan databases, playlists, everything.</p>

                    <h6 class="fw-bolder mt-4 text-danger">REFUNDS</h6>
                    <p>Jeeni can not offer refunds on subscriptions or fees. Someone’s got to pay for all this.</p>

                    <h6 class="fw-bolder mt-4 text-danger">CONTENT YOU CAN UPLOAD</h6>
                    <p>You can upload text, images, video files, audio files, and other content that are either your own copyright, or that you have permission from the copyright-holder. You can change this content as much as you like, as often as you like</p>

                    <h6 class="fw-bolder mt-4 text-danger">CONTENT YOU CANNOT UPLOAD</h6>
                    <p>You cannot submit or upload any content to Jeeni that is obscene, illegal, threatening, defamatory, racist, sexist, phobic or otherwise offensive. You cannot submit or upload any content to Jeeni that invades privacy or infringes the intellectual property of any other person, group or organisation. You cannot submit or upload any content to Jeeni that contains software viruses, mass mailings, spam, fake news or upsetting images. You cannot impersonate any other artist, performer, producer, studio, brand, person or entity, in such a way as to mislead other users of Jeeni as to your identity and the origin of your material. You cannot use a false email address or impersonate any of the above to contact third parties via Jeeni.</p>

                    <h6 class="fw-bolder mt-4 text-danger">CONTENT AND USAGE  RIGHTS</h6>
                    <p>You grant Jeeni the right to use the processor, bandwidth, and storage hardware on your devices in order to facilitate the operation of our service and to provide other information to you from us, our partners and our members.</p>
                    <p>By submitting and uploading content, you grant Jeeni a non-exclusive, world-wide, royalty-free, full license to reproduce, use, modify, publish, adapt, translate, create derivative works from, distribute, and display such content using any Jeeni media. By submitting and uploading content, you warrant and covenant that you own all rights to or have permission to use the content that you submit, and that use of the content will not cause injury to any person or entity. You agree to indemnify, hold harmless and defend Jeeni, and its owners, management, employees and agents from and against any action, claim, demand, dispute, or liability, including reasonable legal fees and costs, arising from or relating to any allegation that your content infringes a third person’s copyright, trademark or proprietary or intellectual property right, or misappropriates a third person’s trade secrets. You further agree that Jeeni shall have the right to defend ourselves against any such claim through counsel of our own choosing.</p>
                    <p>Jeeni may, but has no obligation to, monitor, review, or edit your content. In all cases, Jeeni reserves the right to remove or disable access to your content for any or no reason, including your content that, in Jeeni’s sole discretion, violates these terms and conditions. Jeeni may take action without prior notification to you or any third party. Removal or disabling of access to your content will be at our sole discretion, and we do not promise to remove or disable access to any specific content.</p>
                    <p>You are solely responsible for all the content that you post on Jeeni. Jeeni is not responsible for any of your content nor does it endorse any opinion contained in any of your content. You agree that if anyone brings a claim against Jeeni related to any content that you post, then to the extent permissible under local law, you will indemnify and hold Jeeni harmless from and against all damages, losses, and expenses of any kind.</p>
                    <p>If you provide feedback, ideas, or suggestions to Jeeni in connection with the Jeeni service or content, you acknowledge that this is not confidential and you authorise Jeeni to use this without restriction and without payment to you, although you may be rewarded for your activities on Jeeni under any specific Rewards system.</p>

                    <h6 class="fw-bolder mt-4 text-danger">REPORTING AND REPORTED ABUSE</h6>
                    <p>You may report any abuse that you believe is taking place concerning content uploaded to Jeeni by third-parties, using the Report This Track button underneath every video,  and your report will be investigated and acted on if substantiated. If you report abuse maliciously, and your report is found to be false, we reserve the right to cancel your membership of Jeeni without notice. Similarly we will investigate any reports of abuse made against content you submit and upload. If we consider that any such content breaks any of the conditions set out above, we reserve the right to remove your content without any explanation, any discussion or any refund of paid content or services you may have subscribed to.</p>

                    <h6 class="fw-bolder mt-4 text-danger">THIRD-PARTY AGREEMENTS AND DISPUTES</h6>
                    <p>The Jeeni platform and service may be integrated and interact with third-party applications, code, websites, services, devices and whatnot to make our Jeeni service available to you. These may have their own terms and conditions of use and privacy policies, and your use of them will be governed by and subject to their own terms and conditions and privacy policies. You understand and agree that Jeeni does not endorse and is not responsible or liable for the behaviour, features, or content of any third-party stuff or for any transaction you may enter into with their provider, nor does Jeeni warrant the compatibility or continuing compatibility of any third-party stuff with our service.</p>
                    <p>We will not become involved in any agreements or disputes between artists, subscribers, members, affiliates, or any other third-party contributing to Jeeni, and we take no responsibility for failure by third-parties to perform, deliver, supply or adhere to any agreements made by them. Similarly, we can take no responsibility for the content of any third-party content or service that Jeeni links to, or that subscribers and members link to via Jeeni. You specifically agree that Jeeni is not responsible for any content, associated links, resources, or services associated with any third-party. You further agree that Jeeni will not be liable for any loss or damage of any sort associated with your use of third-party content.</p>
                    <p>Similarly, Jeeni will not become involved in any agreements, promises, claims, fulfilments or discussions made between Artists or Pros and their fans, their audiences or members of the public. If Jeeni Artists and Pros solicit or receive funds or donations from any third party, that’s great, but Jeeni will not become involved or take any responsibility for such activities.</p>

                    <h6 class="fw-bolder mt-4 text-danger">DISCLAIMER</h6>
                    <p>All content, services, products, software and usages on this platform or associated with Jeeni are provided as is, and without warranty of any kind, either express or implied, including, without limitation, those of fitness for purpose, non-infringement and merchantability. Jeeni does not warrant that the descriptions and content concerning artists, performers, products and services offered will necessarily meet your requirements, and neither can we guarantee that content uploaded by members, subscribers or anyone else is necessarily honest, truthful, legal and decent. Think of us as match-makers, where we do our best to make the best introductions we can, but we cannot possibly guarantee a blissful relationship. Jeeni, our suppliers, associates and personnel will not be liable for any direct, indirect, special, consequential, incidental or punitive damages, in any circumstances. Also, while we will always try to provide our services and access to Jeeni to the best of our ability, we cannot guarantee that such services and access will be available for 100% of the time for any reason, including, but not limited to service outages, accident, force majeure or negligence. Neither Jeeni nor its owners, shareholders or investors will be held liable for any costs or damages including, but not limited to, indirect, special, incidental, exemplary or consequential damages (including, without limitation, lost profits) related to these Terms and Conditions or resulting from your use or inability to use Jeeni, arising from any cause whatsoever, even if Jeeni has been notified of the possibility of such damages.</p>

                    <h6 class="fw-bolder mt-4 text-danger">INDEMNITY</h6>
                    <p>You agree to indemnify, hold harmless and defend Jeeni and our owners, directors, managers, employees and agents from and against any action, claim, demand, dispute, or liability, including reasonable legal fees and costs, arising from or relating to your breach of these Terms and Conditions, your negligence or deliberate misconduct, or any allegation that the content infringes a third person’s copyright, trademark or proprietary or intellectual property right, or misappropriates a third person’s trade secrets.</p>

                    <h6 class="fw-bolder mt-4 text-danger">GOVERNING LAW</h6>
                    <p>These Terms and Conditions shall be governed by and construed in accordance with the laws of the United Kingdom. You agree that any legal action or proceeding under or with respect to these Terms and Conditions will be brought in the United Kingdom, and you hereby submit to the jurisdiction of such courts. You also agree not to bring any legal action or proceeding under or with respect to these Terms and Conditions in any other territory.</p>

                    <h6 class="fw-bolder mt-4 text-danger">LOCAL LAWS AND REGULATIONS</h6>
                    <p>Subscribers, members and users of Jeeni are responsible for investigating and adhering to all local laws and regulations including, but not limited to, copyright, advertising, permits, licenses, taxes, and safety compliance.</p>
                    <p>Where permitted under the applicable law, you and Jeeni agree that each may bring claims against the other only in your or Jeeni’s individual capacity and not as a plaintiff or class member in any purported class or representative action. Unless both you and Jeeni agrees, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative or class proceeding.</p>

                    <h6 class="fw-bolder mt-4 text-danger">FORCE MAJEURE</h6>
                    <p>Neither Jeeni nor any party using this website shall be in default by reason of any failure or delay in the performance of any obligation under these Terms and Conditions, where such failure or delay arises out of any cause beyond the control and without the fault or negligence of Jeeni or such party.</p>
                    <!-- // Terms Condition -->
                </div>
            </div>
            <!-- // Content after the title -->
        </div>
        <!-- // Body content -->

    </main>
@endsection
