<?php

return [
    [
        'name' => 'MEL CROUCHER',
        'position' => 'Chairman & Creator Of Jeeni',
        'description' => 'Founder of the UK videogames industry, producer of the world’s first million-user viral campaign, builder of fan databases for global superstars and the Creator of Jeeni.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/mel.png',
    ],
    [
        'name' => 'SHENA MITCHELL',
        'position' => 'C.E.O. LADYBOSS',
        'description' => 'Responsible for raising $25million in private and public funds before she co-founded Jeeni. Driver of investors and audiences that make our artists money, so they can keep 100% of their profits generated through our platform.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/shena.jpeg',
    ],
    [
        'name' => 'KELLI RICHARDS',
        'position' => 'MANAGING DIRECTOR',
        'description' => 'Former A&R Executive EMI Music, mentored by Steve Jobs at Apple, she launched and managed the music and entertainment division, resulting in the birth of global music online, now known as Apple Music.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/keili.png',
    ],
    [
        'name' => 'ROGER WATSON',
        'position' => 'STARMAKER',
        'description' => 'Legendary boss of Arista Records, A&R Director of Chrysalis Records, stage manager for The Beatles, producer of platinum singles and albums on both sides of the Atlantic, responsible for 500 million record sales, and head of Jeeni Awards.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/roger.png',
    ],
    [
        'name' => 'FRANK ZAPPA MITCHELL',
        'position' => 'HEAD OF SECURITY',
        'description' => 'Trained by the legendary Rufus Finn-Reddins, Frank has a nose for sniffing out threats and can lick any opposition. His message to the world is “Join Jeeni or the duck gets it!”',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/frank.jpg',
    ],
    [
        'name' => 'Ella Venvell',
        'position' => 'MARKETING TEAM LEADER',
        'description' => 'Designer and optimiser of our strategic promotional campaigns in the best interests of Jeeni artists, whether they are world-class celebrities or brand new talent, handling our artists with dignity, honesty and respect.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/ella.jpg',
    ],
    [
        'name' => 'HARIS CHAUDHRY',
        'position' => 'TECHNICAL PROJECT MANAGER',
        'description' => 'Leader of the Jeeni Development Team delivering of our next-generation technical platforms for mobiles, laptops and desktops.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/haris.jpg',
    ],
    [
        'name' => 'MIKE NAHLIK',
        'position' => 'SENIOR DEVELOPER',
        'description' => 'Back-end wrangler of the new Jeeni platform to power us into the future. Master of the server. Linux Enthusiast. Our artist showcases and fan databases are in expert hands.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/mike.jpeg',
    ],
    [
        'name' => 'DOREEN OLYMPIO',
        'position' => 'ARTIST LIAISON',
        'description' => 'Promoting and managing the relationships between Jeeni and our artists, and handling our Inside Story video interviews.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/doreen.jpg',
    ],
    [
        'name' => 'ZAK AHMED',
        'position' => 'HUMAN RESOURCES MANAGER',
        'description' => 'Working in the best interests of Team Jeeni, so we can work in the best interests of our members. Master of Business with Honours in Management, and the calmest eye in any storm.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/zak.jpg',
    ],
    [
        'name' => 'DOUG PHILLIPS',
        'position' => 'POET LAUREATE',
        'description' => 'Dipping his pen in the lifeblood of contemporary music and the arts, our scribe for  Jeeni reviews, blogs and media analysis.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/doug.png',
    ],
    [
        'name' => 'ELLIOT RILEY',
        'position' => 'PARTNERSHIP CO-ORDINATOR',
        'description' => 'Advancing the Jeeni cause at the sharp end, handling our partnership liaisons with artists, events, experts and professionals.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/elliot.jpg',
    ],
    [
        'name' => 'HARJEET KANG',
        'position' => 'PERSONNEL LIAISON',
        'description' => 'Our outreach manager and communicator between members of Team Jeeni, our Partners, Investors, and of course our artists and performers.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/harjeet.jpg',
    ],
    [
        'name' => 'STEVEN LIN',
        'position' => 'PLATFORM PERFECTOR',
        'description' => 'Creator and manager of the hands-on user experience for our upcoming new platform, across all formats.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/steven.jpg',
    ],
    [
        'name' => 'JITEN PATEL',
        'position' => 'PROGRAMMING CATALYST',
        'description' => 'Our failsafe coder, making sure that our upcoming new platform is nothing short of perfection.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/jiten.png',
    ],
    [
        'name' => 'AURY SILVA',
        'position' => 'FRONT-END CODER',
        'description' => 'Responsible for turning our designs and concepts into the smoothest user experience. He also oversees our automated email and marketing systems.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/aury.png',
    ],
    [
        'name' => 'DOM HILL',
        'position' => 'TALENT SCOUT',
        'description' => 'Identification and liaison with brand new talent and upcoming stars, via live performance and online auditions.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/dom.jpg',
    ],
    [
        'name' => 'BAQIR ALI',
        'position' => 'Graphic Designer',
        'description' => 'The visionary and originator of the concept designs for the new Jeeni website.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/baqir.jpg',
    ],
    [
        'name' => 'ANNESA SUKUL',
        'position' => 'SOCIAL MEDIA MARKETING',
        'description' => 'Campaign architect for our partnerships with the organisations who share our vision and ethics.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/anessa.jpeg',
    ],
    [
        'name' => 'BIVEK SHRESTHA',
        'position' => 'PLATFORM DEVELOPER',
        'description' => 'Backup coder to the Jeeni technical development team.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/bivek.png',
    ],
    [
        'name' => 'LEE SCOTT',
        'position' => 'ACCOUNTANT',
        'description' => ' MBA, AAT, ICB and CIMA, working in the best interests of our artists, our team and our investors.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/lee.png',
    ],
    [
        'name' => 'SHARRON GOODYEAR',
        'position' => 'IMAGE WELDER',
        'description' => 'Master Photographer Association – Photographer of the Year Winner, with a global client base. Jeeni Official Photographer for artists, performers, promotions and events. Specialist in online virtual shoots.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/sharron.jpg',
    ],
    [
        'name' => 'ANTHONY ROSE',
        'position' => 'LEGAL PARTNER',
        'description' => 'Responsible for the launch of the BBC iPlayer, and legal adviser to Jeeni. He is CEO of the award-winning Seed Legals, the largest legal platform for start-ups in the UK.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/anthony.jpg',
    ],
    [
        'name' => 'BEN MILES',
        'position' => 'HARDWARE PARTNER',
        'description' => 'MD of Chillblast, the UK’s most highly-awarded PC manufacturer, producer of Jeeni-branded specialist computers for musicians, producers, mixers, photographers and videographers.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/ben.jpg',
    ],
    [
        'name' => 'SKYLER JETT',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Record of the Year Winner, Grammy Award Winner, founder of Music For Global Change, “Unifying, bringing awareness, breaking down the barriers of racism using the gift of music.”',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/skyler.jpeg',
    ],
    [
        'name' => 'EDDIE LEVY',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Founder of ATV Music (owners of the Beatles catalogue), owner of Chelsea Music, representing stars like Roberta Flack, Jeff Beck and Andrea Bocelli, and ready to represent our new generation of Jeeni stars for commercials and soundtracks.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/eddie.png',
    ],
    [
        'name' => 'ELLIE MILNER',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Global Director of Arms Around The Child, in partnership with Europe’s largest and most successful music college, integral to Jeeni ethics policies and charity collaborations helping young people.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/ellie.jpg',
    ],
    [
        'name' => 'ROMILLY NOLAN',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Actress, model, superconnector to the music and entertainment world, and one of the lead investors in the Jeeni project.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/romilly.jpeg',
    ],
    [
        'name' => 'TONY KLINGER',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Lifetime Achievement Award for media executive work from The Avengers to The Who and Deep Purple. “I am proud and excited to be an Ambassador for Jeeni. Together we are stronger, can do more, and share our knowledge and passion.”',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/tony.jpg',
    ],
    [
        'name' => 'TEDDY HAYES',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'Award-winning producer, film-maker and composer, and founding director of Hip Hop. “I want Jeeni artists to get the recognition they deserve and earn cash in the process.”',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/teddy.jpg',
    ],
    [
        'name' => 'JOHN ALTMAN',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'The musician’s musician. Royal Philharmonic Orchestra conductor, hit record maker for Bjork, George Michael, Quincy Jones, Diana Ross, Jimi Hendrix, Muddy Waters, Bob Marley, Eric Clapton, Little Richard, Van Morrison … everyone who’s anyone.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/john.jpg',
    ],
    [
        'name' => 'ZEETEAH MASSIAH',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'No. 1 chart-topper in America, jazz diva, reggae star, world tours with Michael Jackson, Tom Jones, Sting, Robbie Williams, Paul Weller, Johnny Hallyday, Phil Collins, Michael Bolton.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/zeetah.jpg',
    ],
    [
        'name' => 'PAUL CAPLIN',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'The Voice of Reason to balance the more bizarre ideas of Jeeni’s creator. Entrepreneur of the Year award-winner, information technology mogul.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/paul.jpg',
    ],
    [
        'name' => 'STEVE SALVARI',
        'position' => 'JEENI AMBASSADOR',
        'description' => 'The go-to guy for artist development and music production, Steve has worked with a host of superstars including Chaka Khan, Barry White, Billy Ocean, Lulu, Aswad, Natalie Cole and Robert Palmer.',
        'image' => 'https://jeeni-22.s3.eu-west-2.amazonaws.com/team/steve.jpg',
    ]
];
